{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{ezcss_require( array('spectrum.css' ) )} 
{ezscript_require( array( 'ezjsc::jquery', 'spectrum.js', 'colourpicker.js' ) )}

{default attribute_base='ContentObjectAttribute'
         html_class='full'}

<input 
    id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
    name="{$attribute_base}_sfcolourpicker_data_text_{$attribute.id}" value="{$attribute.data_text|wash( xhtml )}"
    class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier} colourPicker" 
    type="text" 
    size="70"
    maxlength="7"
/>

{/default}
